### PR TITLE
Support large feature tables

### LINKED ISSUE #19: RAMClustR fails if run on large feature table.
If supplying a feature table with more than 55k entries, RAMClustR fails due to this issue in the ff package [ref](https://github.com/truecluster/ff/issues/3). I doubt this issue in ff will be fixed.

Since this allocated matrix is symmetric (I assume at least), and only the upper triangle is computed anyway, I think this computation could maybe be optimized in order to never have to store the actual full matrix in memory.

@cbroeckl if you are currently busy and don't have the time to address this issue I'd be happy to support and we will come up with an implementation to solve this.

https://github.com/cbroeckl/RAMClustR/blob/351243d9bb98da7ae684580c8e0fe2f911482190/R/ramclustR.R#L667

### PR DESCRIPTION
**Pull request by xtrojak**
This PR solves issue #19 - package `ff` fails on the allocation of the correlation matrix for large feature tables with dimensions greater than `.Machine$integer.max`  ([details](https://github.com/truecluster/ff/issues/3)).

The solution was to avoid allocating the whole matrix and thus using the `ff` package. The idea was to compute only intermediate matrices and store them in the output vector. More details of the algorithm _before_ and _after_ this PR are outlined in the picture below (sorry for the low quality, it's just a sketch).

Also added simple integration test of main functionality and `conda` environment file for local testing.

Close #19.

Notes

### CODE REVIEW

**Comment by sneumann** [comment]
Hi, I saw that you included a testthat case, that's great. So I guess that both old and new approach will pass the test and give identical results ? Yours, Steffen

**Comment by cbroeckl** [comment]
Thanks Steffen - i appreciate you jumping in for this.  I am new to this process!   The 'identical results' question is the one i was to ask as well.

**Comment by xtrojak** [comment]
Hi. Yes, the integration test is passing in both versions.

I also refactored and extracted function for computing the similarity. We could write unit tests for this, although it is not easy to compare it with the old version.

**Comment by cbroeckl** [comment]
I am not clear what the 'integration test' is testing, precisely.  I also am not clear what you mean by 'refactored and extracted function for computing similarity'.   The similarity score should not have to have been changed to make the integer.max problem go away?

Comparing with the old version:

It would be pretty easy to test the ultimate results:

Identical(rc.old$featclus, rc.new$featclus)
Identical(rc.old$fmz, rc.new$fmz)

If those to things are identical, we can be pretty confident the rest is too.

**Comment by cbroeckl** [comment]
@xtrojak i see the commit for testing: 

> expect_equal(readLines(expected_msp), readLines(actual_msp))

and it would certainly seem true that if the new .msp file is identical to the old .msp file that the clustering is identical.   did your test compare the original vs the updated and passed?

**Comment by xtrojak** [comment]
@cbroeckl sorry if my answer was confusing. The expected output in `"testdata/output.msp"` was created using the old version (currently in `master`) and is being compared to a `msp` file created using the new version in the test.

**Comment by cbroeckl** [comment]
@xtrojak - thanks!  i will merge, do some testing locally, and push the new version to CRAN.  It may take me a couple of days.

**Comment by hechth** [comment]
@cbroeckl Thank you very much! Yes, we verify that if we re-write an algorithm or so that the outputs of the tool/algorithm don't change so that they are equivalent. Refactoring means changing code structure without changing function 👍

We already had tests in place for our Galaxy tool, so we basically took those and put them into the actual RAMClustR code to check if the results are consistent.

**Comment by cbroeckl** [comment]
@xtrojak and @hechth - thanks for your contributions.  I am glad that you are finding it valuable enough to continue to invest time into it!

**Pull request merged**
